pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                bat 'build.bat'
            }
        }

        stage('Run') {
            steps {
                bat 'run.bat'
            }
        }
    }
}
